---
# Create a security group
- name: Create a security group
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ security_groups }}'

- name: Create a list of security group names
  set_fact:
    sg_names: '{{ sg_names|default([]) + [ item.name ] }}'
  loop: '{{ security_groups }}'

- debug:
    msg: "Security group(s) {{ sg_names }} have been created."


- name: grp05_ssh
  os_security_group_rule:
    security_group: COMP90024-grp05
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
    state: present

- name: grp05_http
  os_security_group_rule:
    security_group: COMP90024-grp05
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
    state: present


- name: grp05_cluster port 5986
  os_security_group_rule:
    security_group: COMP90024-grp05
    protocol: tcp
    port_range_min: 5986
    port_range_max: 5986
    remote_ip_prefix: 0.0.0.0/0
    state: present


- name: grp05_cluster port 4369
  os_security_group_rule:
    security_group: COMP90024-grp05
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
    state: present


- name: grp05_couchDB
  os_security_group_rule:
    security_group: COMP90024-grp05
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
    state: present

- name: grp05_cluster port 9100-9200
  os_security_group_rule:
    security_group: COMP90024-grp05
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0
    state: present





